//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflows.SentimentReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aic.service.sentiment/", ConfigurationName="SentimentReference.ISentiment")]
    public interface ISentiment {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ComputeAverage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Workflows.SentimentReference.ComputeAverageResponse ComputeAverage(Workflows.SentimentReference.ComputeAverage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ComputeAverage", ReplyAction="*")]
        System.Threading.Tasks.Task<Workflows.SentimentReference.ComputeAverageResponse> ComputeAverageAsync(Workflows.SentimentReference.ComputeAverage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Compute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Workflows.SentimentReference.ComputeResponse Compute(Workflows.SentimentReference.Compute request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Compute", ReplyAction="*")]
        System.Threading.Tasks.Task<Workflows.SentimentReference.ComputeResponse> ComputeAsync(Workflows.SentimentReference.Compute request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComputeAverage", WrapperNamespace="http://aic.service.sentiment/", IsWrapped=true)]
    public partial class ComputeAverage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] texts;
        
        public ComputeAverage() {
        }
        
        public ComputeAverage(string[] texts) {
            this.texts = texts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComputeAverageResponse", WrapperNamespace="http://aic.service.sentiment/", IsWrapped=true)]
    public partial class ComputeAverageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double averageSentiment;
        
        public ComputeAverageResponse() {
        }
        
        public ComputeAverageResponse(double averageSentiment) {
            this.averageSentiment = averageSentiment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Compute", WrapperNamespace="http://aic.service.sentiment/", IsWrapped=true)]
    public partial class Compute {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string text;
        
        public Compute() {
        }
        
        public Compute(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComputeResponse", WrapperNamespace="http://aic.service.sentiment/", IsWrapped=true)]
    public partial class ComputeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double sentiment;
        
        public ComputeResponse() {
        }
        
        public ComputeResponse(double sentiment) {
            this.sentiment = sentiment;
        }
    }
}
