//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceActivities.AccountingReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aic.service.accounting/", ConfigurationName="AccountingReference.IAccounting")]
    public interface IAccounting {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetOurAccountData", ReplyAction="*")]
        ServiceActivities.AccountingReference.GetOurAccountDataResponse GetOurAccountData(ServiceActivities.AccountingReference.GetOurAccountData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetOurAccountData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceActivities.AccountingReference.GetOurAccountDataResponse> GetOurAccountDataAsync(ServiceActivities.AccountingReference.GetOurAccountData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Charge", ReplyAction="*")]
        ServiceActivities.AccountingReference.ChargeResponse Charge(ServiceActivities.AccountingReference.Charge request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Charge", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceActivities.AccountingReference.ChargeResponse> ChargeAsync(ServiceActivities.AccountingReference.Charge request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetBill", ReplyAction="*")]
        ServiceActivities.AccountingReference.GetBillResponse GetBill(ServiceActivities.AccountingReference.GetBill request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetBill", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceActivities.AccountingReference.GetBillResponse> GetBillAsync(ServiceActivities.AccountingReference.GetBill request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOurAccountData", WrapperNamespace="http://aic.service.accounting/", IsWrapped=true)]
    public partial class GetOurAccountData {
        
        public GetOurAccountData() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOurAccountDataResponse", WrapperNamespace="http://aic.service.accounting/", IsWrapped=true)]
    public partial class GetOurAccountDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ourAccountData;
        
        public GetOurAccountDataResponse() {
        }
        
        public GetOurAccountDataResponse(string ourAccountData) {
            this.ourAccountData = ourAccountData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Charge", WrapperNamespace="http://aic.service.accounting/", IsWrapped=true)]
    public partial class Charge {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double amount;
        
        public Charge() {
        }
        
        public Charge(string companyName, double amount) {
            this.companyName = companyName;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeResponse", WrapperNamespace="http://aic.service.accounting/", IsWrapped=true)]
    public partial class ChargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool chargingSucceeded;
        
        public ChargeResponse() {
        }
        
        public ChargeResponse(bool chargingSucceeded) {
            this.chargingSucceeded = chargingSucceeded;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBill", WrapperNamespace="http://aic.service.accounting/", IsWrapped=true)]
    public partial class GetBill {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string companyName;
        
        public GetBill() {
        }
        
        public GetBill(string companyName) {
            this.companyName = companyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillResponse", WrapperNamespace="http://aic.service.accounting/", IsWrapped=true)]
    public partial class GetBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double currentBill;
        
        public GetBillResponse() {
        }
        
        public GetBillResponse(double currentBill) {
            this.currentBill = currentBill;
        }
    }
}
