//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceActivities.UserReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aic.service.user/", ConfigurationName="UserReference.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Remove", ReplyAction="*")]
        ServiceActivities.UserReference.RemoveResponse Remove(ServiceActivities.UserReference.Remove request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceActivities.UserReference.RemoveResponse> RemoveAsync(ServiceActivities.UserReference.Remove request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Exists", ReplyAction="*")]
        ServiceActivities.UserReference.ExistsResponse Exists(ServiceActivities.UserReference.Exists request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Exists", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceActivities.UserReference.ExistsResponse> ExistsAsync(ServiceActivities.UserReference.Exists request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CheckCredentials", ReplyAction="*")]
        ServiceActivities.UserReference.CheckCredentialsResponse CheckCredentials(ServiceActivities.UserReference.CheckCredentials request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CheckCredentials", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceActivities.UserReference.CheckCredentialsResponse> CheckCredentialsAsync(ServiceActivities.UserReference.CheckCredentials request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        ServiceActivities.UserReference.AddResponse Add(ServiceActivities.UserReference.Add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceActivities.UserReference.AddResponse> AddAsync(ServiceActivities.UserReference.Add request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remove", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class Remove {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string companyName;
        
        public Remove() {
        }
        
        public Remove(string companyName) {
            this.companyName = companyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveResponse", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool userRemoved;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(bool userRemoved) {
            this.userRemoved = userRemoved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Exists", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class Exists {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string companyName;
        
        public Exists() {
        }
        
        public Exists(string companyName) {
            this.companyName = companyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExistsResponse", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class ExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool userExists;
        
        public ExistsResponse() {
        }
        
        public ExistsResponse(bool userExists) {
            this.userExists = userExists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCredentials", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class CheckCredentials {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public CheckCredentials() {
        }
        
        public CheckCredentials(string companyName, string password) {
            this.companyName = companyName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCredentialsResponse", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class CheckCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool credentialsValid;
        
        public CheckCredentialsResponse() {
        }
        
        public CheckCredentialsResponse(bool credentialsValid) {
            this.credentialsValid = credentialsValid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class Add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public Add() {
        }
        
        public Add(string companyName, string password) {
            this.companyName = companyName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://aic.service.user/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool userAdded;
        
        public AddResponse() {
        }
        
        public AddResponse(bool userAdded) {
            this.userAdded = userAdded;
        }
    }
}
